### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by mattmezza** [kottenator/jquery-circle-progress#14]
Hi there, 
first of all thank you for the great plugin.

This issue is related to Safari. The arc is not well painted (colors and shape - it has not rounded lines). I'm posting here some pics...
![screen shot 2015-01-13 at 6 56 13 pm](https://cloud.githubusercontent.com/assets/1915989/5725753/08bdda14-9b56-11e4-8ade-973cf602802d.png)

![screen shot 2015-01-13 at 6 55 59 pm](https://cloud.githubusercontent.com/assets/1915989/5725751/01a306aa-9b56-11e4-8e5f-71c618ef33ec.png)

![screen shot 2015-01-13 at 6 53 13 pm](https://cloud.githubusercontent.com/assets/1915989/5725730/c15df96a-9b55-11e4-9dd1-12151b16393a.png)

This does not occur using Chrome, where the canvas is rendered perfectly.
![screen shot 2015-01-13 at 6 59 28 pm](https://cloud.githubusercontent.com/assets/1915989/5725811/75692c86-9b56-11e4-82af-375fbeed9a0d.png)

The application is developed using [Polymer](polymer-project.org). Might it be a compatibility problem?

**Comment by kottenator** [comment]
Could you, please, give me the code fragment and exact version of Safari and OS that you use? (so I could reproduce the bug)

**Comment by mattmezza** [comment]
Safari version is: Version 8.0.2 (10600.2.5)
I have this Polymer element 
```html
<polymer-element name="gm-circle-progress" attributes="percentage numcfu">
    <template>
        <!-- CSS -->
        <link rel="stylesheet" href="circular-progress/progress.css">
        <div id="pieProgress" class="pie_progress" role="progressbar" data-goal="{{percentage}}" style="margin-bottom: 20px;" data-speed="35" data-barsize="7" data-barcolor="#0943a0">
            <div id='percentage' class="pie_progress__number">{{percentage}}</div>
            <div id='numcfu' class="pie_progress__label">{{numcfu}} CFU</div>
        </div>
    </template>
    
    <!-- JS -->
    <script src="../../bower_components/jquery-circle-progress/dist/circle-progress.js"></script>
    <script src="main.js"></script>
</polymer-element>
```
css linked is this
```css
.pie_progress {
  text-align: center;
  position: relative;
  -webkit-transform-style: preserve-3d;
          transform-style: preserve-3d;
}
.pie_progress svg {
  margin: 0 auto;
}
.pie_progress__content,
.pie_progress__number,
.pie_progress__label,
.pie_progress__icon {
  width: 100%;
  position: absolute;
  top: 50%;
  left: 0;
  -webkit-transform: translateY(-50%);
      -ms-transform: translateY(-50%);
       -o-transform: translateY(-50%);
          transform: translateY(-50%);
}
.pie_progress__number {
  font-size: 42px;
}
.pie_progress__label {
  margin-top: 32px;
  font-size: 12px;
}
```
and the js file linked (apart from the plugin itself) is this:
```javascript
Polymer('gm-circle-progress', {
    percentage: 0,
    numcfu: "0/180",
    observe: {
    	percentage: 'go'
    },
    
    ready: function() {
    },
    
    go: function() {
    	this.$.pieProgress.percentage = this.$.percentage;
		$(this.$.pieProgress).circleProgress({
            value: this.percentage/100,
            size: 140,
            startAngle: -Math.PI/2,
            fill: {
            	color: ['#0943a0']
            }
        }).on('circle-animation-progress', function(event, progress, stepValue) {
            $(this.percentage).html(parseInt(100 * stepValue) + '%');
        });
	}
});
```

The web component is instanced in a web page as follows:
```html
...
<body>
...
<gm-circle-progress id="circleProgress" percentage="100" numcfu="180"></gm-circle-progress>
...
</body>
...
```
if you want you can browse the code from GitHub at this [link](https://github.com/giograno/myUnimol_webApp/tree/develop/web/our_components/gm-circle-progress).
