### ISSUE TITLE
Numbers in Circle

### ISSUE THREAD

**Issue by qwer4k** [kottenator/jquery-circle-progress#161]
Hello, first of all thank you very much. After spent 1 week, finally i found the correct jquery . My problem was to show animation when you scroll down to div. I solved this problem with **jquery-appear**.

So now i need to add numbers which counts dynamically in circle. I know maybe it's easy and read some closed posts here but my jquery information is very bad so i don't know how to add. I have 3 circle with different percents.

Here are my codes.

```html
<div class="circle one" data-fill="&quot;#f55&quot;"></div> 
<div class="circle two" data-fill="&quot;#f55&quot;"></div> 
<div class="circle three" data-fill="&quot;#f55&quot;"></div>
```

```css
.circle { 
  width: 50px; 
  height: 50px; 
  border-radius: 100%; 
  box-shadow: inset 0 0 0 42px #fff, inset 0 0 0 44px #ccc, 0 0 0 2px #fff, 0 0 0 4px #ccc; 
}
```

```js
var circles = $('.circle');

circles.appear({ force_process: true });

circles.on('appear', function() {
  var circle = $(this);
  if (!circle.data('inited')) {
    circle.circleProgress({
      value: 1,
      size: 50,
      thickness: 10
    });
    circle.data('inited', true);
  }
});
```

**Comment by kottenator** [comment]
@qwer4k - on the project [landing page](http://kottenator.github.io/jquery-circle-progress/) - see the middle circle - is this what you want? then just do:

```html
<div class="circle one">
  <span class="value"></span>
</div>
<div class="circle two">
  <span class="value"></span>
</div> 
<div class="circle three">
  <span class="value"></span>
</div>
```

```css
.circle {
  position: relative;
  width: 50px; 
  height: 50px; 
  border-radius: 100%; 
  box-shadow: inset 0 0 0 42px #fff, inset 0 0 0 44px #ccc, 0 0 0 2px #fff, 0 0 0 4px #ccc; 
}

.circle .value {
  position: absolute;
  top: 6px;
  left: 0;
  right: 0;
  text-align: center;
  line-height: 40px;
  font-size: 14px;
}
```

```js
var circles = $('.circle');

circles.appear({ force_process: true });

circles.on('appear', function() {
  var circle = $(this);

  if (!circle.data('inited')) {
    circle.circleProgress({
      value: 1,
      size: 50,
      thickness: 10,
      fill: "#f55"
    });

    circle.data('inited', true);

    circle.on('circle-animation-progress', function(event, progress, stepValue) {
      $(this).find('.value').text((100 * stepValue).toFixed());
    });
  }
});
```
