### ISSUE TITLE
how to print text inside circle

### ISSUE THREAD

**Issue by stardust01** [kottenator/jquery-circle-progress#175]
how to print text and fa-fa icons inside circle .

**Comment by kottenator** [comment]
Hi, @stardust01!

There're numerous ways how to do it. For example:

```html
<div class="circle">
  <strong class="value"></strong>
</div>
```

```css
.circle {
  width: 100px;
  position: relative;
}

.circle .value {
  position: absolute;
  top: 30px;
  left: 0;
  width: 100%;
  text-align: center;
  line-height: 40px;
  font-size: 30px;
}
```

```js
$('.circle').circleProgress({
  value: 0.75,
}).on('circle-animation-progress', function(event, progress, stepValue) {
  $(this).children('.value').text(stepValue.toFixed(2));
});
```
