### ISSUE TITLE
Animation Start event doesn't seem to be working

### ISSUE THREAD

**Issue by LNCH** [kottenator/jquery-circle-progress#33]
I could be doing something wrong here, but I'm trying to use the first even in the docs, the circle-animation-start one, and it doesn't appear to be working

Essentially what I'm trying to do is find the dimensions of the canvas object and set the position of my counter to be in the center of the circle. I could do it through the CSS but I want it to be set regardless of the size I choose. Any ideas?

**Comment by kottenator** [comment]
**First:** I've checked and the event works fine:
```js
var el = $('.circle-container').circleProgress({ value: 0.5 });
el.on('circle-animation-start', function () { console.log('animation started'); });
el.on('circle-animation-end', function () { console.log('animation finished'); });
```
**Second:** what you want to do is definitely should be done via CSS, like so:
```css
.circle-container {
    position: relative;
    /* you don't have to set width and height */
}

.circle-container .middle-block {
    position: absolute;
    left: 50%;
    top: 50%;
    width: 20px;
    height: 20px;
    margin: -10px 0 0 -10px;
    border-radius: 10px;
    background-color: rgba(0, 0, 0, .5);
}
```
